// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package fileproperties

type PropertyPrefetchOptions uint32

const SignaturePropertyPrefetchOptions string = "enum(Windows.Storage.FileProperties.PropertyPrefetchOptions;u4)"

const (
	PropertyPrefetchOptionsNone               PropertyPrefetchOptions = 0
	PropertyPrefetchOptionsMusicProperties    PropertyPrefetchOptions = 1
	PropertyPrefetchOptionsVideoProperties    PropertyPrefetchOptions = 2
	PropertyPrefetchOptionsImageProperties    PropertyPrefetchOptions = 4
	PropertyPrefetchOptionsDocumentProperties PropertyPrefetchOptions = 8
	PropertyPrefetchOptionsBasicProperties    PropertyPrefetchOptions = 16
)
