// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type UIStatus int32

const SignatureUIStatus string = "enum(Windows.Storage.Provider.UIStatus;i4)"

const (
	UIStatusUnavailable UIStatus = 0
	UIStatusHidden      UIStatus = 1
	UIStatusVisible     UIStatus = 2
	UIStatusComplete    UIStatus = 3
)
